version: '3'

networks:
  db:
  web:
    external:
      name: web

services:
  mongo:
    image: mongo
    networks:
      - db
  rsjweb:
    image: rsj
    volumes:
      - './rsj/:/app/'
    labels:
      - 'traefik.HTTP.Routers.RSJ.Rule=Host(`dev.readysetjazz.com`)'
      - 'traefik.HTTP.Routers.RSJS.Rule=Host(`dev.readysetjazz.com`)'
      - 'traefik.HTTP.Routers.RSJS.tls=true'
      - 'traefik.HTTP.Routers.RSJ.middlewares=redirect'
      - 'traefik.docker.network=web'
    networks:
      - db
      - web
    depends_on:
      - mongo
    tty: true
