version: '3'

services:
  mongo:
    image: mongo
    networks:
      - db
  web:
    image: rsj
    ports:
      - "8000:80"
    networks:
      - db
    depends_on:
      - mongo
    tty: true
networks:
  db:
