version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ngx
    volumes:
      - rsj.conf:/etc/nginx/sites-enabled/rsj.conf:ro

  web:
    image: rsj
    ports:
      - "8000:8000"
    volumes:
      - rsj:/rsj
    networks: 
      - ngx
  mongo:
    image: mongo
    networks: 
      - ngx

volumes:
  rsj:
  rsj.conf:

networks:
  ngx:
